---
title: "Housing"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}

library(siverse)
library(tidyverse)
library(googlesheets)
library(leaflet)
library(billboarder)
library(plotly)
library(scales)
library(tidycensus)
library(crayon)
library(tigris)
library(sf)
library(stringr)

```


```{r acs fn}

acsvars <- load_variables(2017, "acs5", cache = T) %>%
  mutate(level = str_count(label, pattern = "!!")) %>%
  rowwise() %>%
  mutate(levlab = str_split(label, pattern = "!!") %>% unlist() %>% .[level + 1]) %>%
  ungroup() %>%
  mutate(concept = str_to_title(concept)) %>%
  rename(variable = name)


si_acs <- function(table, county = NULL, state = NULL, summary_var = "universe total", geography = NULL, survey = "acs5", geometry = FALSE) {
  cat(yellow(bold("Reminder: You must stay within the same level for any summary to be valid!\n")))
  
  if(summary_var == "universe total") summary_var = paste0(table, "_001")
  summary_label = acsvars %>% filter(variable == summary_var) %>% pull(levlab)
  
  get_acs(geography = geography,
          table = table,
          county = county,
          state = state,
          output = "tidy",
          year = 2017,
          cache_table = T,
          summary_var = summary_var, 
          geometry = geometry, 
          cb = T, 
          survey = survey) %>%
    clean_names() %>%
    left_join(acsvars) %>%
    select(-summary_moe, -variable) %>%
    select(geoid, county = name, level, levlab, estimate, everything()) %>%
    rename(!!summary_label := summary_est)
}



```



```{r Head of household by race}

#B25006 : Race of Householder

hh_race_acs <- si_acs("B25006", state = "NC", geography = "county", county = "Guilford County", survey = "acs1")

hh_race <- hh_race_acs %>% 
  select(-moe) %>% 
  filter(level!=3) %>% 
  filter(level!=1) %>% 
  mutate(levlab =  str_remove(levlab, "Householder who is ")) %>% 
  select(levlab, estimate)

billboarder() %>% 
  bb_donutchart(data = hh_race)

#save(hh_race, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/hh_race.rda")


```


```{r vacant houses map}

#B25002: Occupancy status


#This plots a leaflet map with places

# housing <- si_acs("B25002", geography = "place", state = "NC")%>% rename(GEOID = geoid) %>% filter(levlab == "Vacant")
# 
# summary(housing$estimate)  
# 
# bins <- c(0, 10, 20, 50, 100, 200, 500, 1000, Inf)
# 
geo_places <- county_subdivisions(state = "NC", cb = TRUE, class = "sf")
# 
# plot <- full_join(geo_places, housing)
# pal <- colorQuantile(palette = "viridis", domain = plot$estimate,  probs = seq(0, 1, 0.1))
# plot %>%
#   leaflet() %>% 
#   addPolygons(
#     stroke = F, 
#     fillOpacity = 0.8,
#     fillColor = ~pal( estimate),
#     label = ~ NAME,
#     weight = 2,
#   opacity = 1,
#   color = "white",
#   dashArray = "3",
#   ) %>% 
#   addLegend("bottomright", 
#               pal = pal, 
#               values = ~ estimate,
#               title = "Vacant Houses",
#               opacity = 1)
#   


housing <- si_acs("B25002", geography = "tract", state = "NC", geometry = T)%>% rename(GEOID = geoid) %>% filter(levlab == "Vacant")

pal <- colorQuantile(palette = "viridis", domain = housing$estimate,  probs = seq(0, 1, 0.1))

housing %>% 
  leaflet() %>% 
 
  addPolygons(
    stroke = F,
   
    fillColor = ~pal(estimate), 
    fillOpacity = 1
  ) %>%  
  addPolygons(data = geo_places,
    stroke = T, weight = 1,
    label = ~ NAME, 
    color = "white", 
    dashArray = "3"
  ) %>% 
  addLegend("bottomright",
              pal = pal,
              values = ~ estimate,
              title = "Vacant Houses",
              opacity = 1)
  

```


```{r}


geo_places <- county_subdivisions(state = "NC", cb = TRUE, class = "sf", county = "Guilford County")

vacant_housing <- si_acs("B25002", geography = "tract", state = "NC", geometry = T, county = "Guilford County")%>% rename(GEOID = geoid) %>% filter(levlab == "Vacant")



pal <- colorQuantile(palette = "viridis", domain = vacant_housing$estimate,  probs = seq(0, 1, 0.1))


#leaflet()

vacant_housing %>% 
  leaflet(width = "100%") %>% 
  addProviderTiles(providers$OpenStreetMap.Mapnik) %>% 
   addPolygons(
    stroke = F,
      fillColor = ~pal(estimate), 
    fillOpacity = 1
  ) %>%
  addPolygons(data = geo_places,
    stroke = T, weight = 1,
    label = ~ NAME,
    color = "white",
    dashArray = "3"
  ) %>%
  addLegend("bottomright",
              pal = pal,
              values = ~ estimate,
              title = "Vacant Houses",
              opacity = 1)


#save(vacant_housing, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/vacant_housing.rda")
#save(geo_places, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/geo_places.rda")

```


Renting vs homeowners

```{r}


# A White alone 
# B Black or African American Alone
# C American Indian and Alaska Native Alone
# D Asian Alone
# E Native Hawaiian and Other Pacific Islander Alone
# F Some Other Race Alone
# G Two or More Races
# H White Alone, Not Hispanic or Latino 
# I Hispanic or Latino 


tenure_df <- lst()
  
for(letter in c("A", "B", "C", "D", "E", "F", "G", "H", "I")) {
    tablenum <- paste0("B25003", letter)
    
    df_temp <- si_acs(tablenum, geography = "county", state = "NC", county  = "Guilford County", survey = "acs1") %>% 
      select(county, estimate, label, level, Total) %>% 
      mutate(race = letter) 
    
    tenure_df[[letter]] <- df_temp
}


tenure_gc <- bind_rows(tenure_df)



tenure_gc <- tenure_gc %>% 
  filter(level!=1) %>% 
  mutate(race = case_when(race == "A" ~ "White alone",
                          race == "B"~ "Black or African American Alone",
                          race == "C" ~ "American Indian and Alaska Native Alone",
                          race == "D" ~ "Asian Alone",
                          race == "E" ~ "Native Hawaiian and Other Pacific Islander Alone",
                          race == "F" ~ "Some Other Race Alone",
                          race == "G" ~ "Two or More Races",
                          race == "H" ~ "White Alone, Not Hispanic or Latino", 
                          race == "I" ~ "Hispanic or Latino")) %>% 
  rename(location = county)


tenure_df <- lst()
  
for(letter in c("A", "B", "C", "D", "E", "F", "G", "H", "I")) {
    tablenum <- paste0("B25003", letter)
    
    df_temp <- si_acs(tablenum, geography = "place", state = "NC",  survey = "acs1") %>% 
      select(county, estimate, label, level, Total) %>% 
      mutate(race = letter) 
    
    tenure_df[[letter]] <- df_temp
}


tenure_places <- bind_rows(tenure_df)



tenure_places <- tenure_places %>% 
  filter(level!=1) %>% 
  mutate(race = case_when(race == "A" ~ "White alone",
                          race == "B"~ "Black or African American Alone",
                          race == "C" ~ "American Indian and Alaska Native Alone",
                          race == "D" ~ "Asian Alone",
                          race == "E" ~ "Native Hawaiian and Other Pacific Islander Alone",
                          race == "F" ~ "Some Other Race Alone",
                          race == "G" ~ "Two or More Races",
                          race == "H" ~ "White Alone, Not Hispanic or Latino", 
                          race == "I" ~ "Hispanic or Latino")) %>% 
  rename(location = county) %>% 
  filter(str_detect(location, "Greensboro")| str_detect(location, "High"))
  
  
tenure <- bind_rows(tenure_gc, tenure_places)


tenure_race <- tenure %>% 
  filter(!str_detect(race, "Hispanic")) %>% 
  filter(!is.na(Total)) %>% 
  mutate(perc = estimate/Total) %>% 
  mutate(tenure = case_when(str_detect(label, "Owner") ~ "Owner",
                            str_detect(label, "Renter")~"Renter"))  
 


tenure_bb <- tenure_race %>% 
   filter(location == lc) %>% 
  select(race, perc, tenure)

lc <- "Greensboro city, North Carolina"

billboarder() %>% 
  bb_barchart(data = tenure_bb)
  

```

