---
title: "Overview"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}

library(siverse)
library(tidyverse)
library(googlesheets)
library(leaflet)
library(crayon)
library(tidycensus)

```




```{r}


acsvars <- load_variables(2017, "acs1", cache = T) %>%
  mutate(level = str_count(label, pattern = "!!")) %>%
  rowwise() %>%
  mutate(levlab = str_split(label, pattern = "!!") %>% unlist() %>% .[level + 1]) %>%
  ungroup() %>%
  mutate(concept = str_to_title(concept)) %>%
  rename(variable = name)

si_acs <- function(table, county = NULL, state = NULL, summary_var = "universe total", geography = NULL, survey = NULL) {
  cat(yellow(bold("Reminder: You must stay within the same level for any summary to be valid!\n")))
  
  if(summary_var == "universe total") summary_var = paste0(table, "_001")
  summary_label = acsvars %>% filter(variable == summary_var) %>% pull(levlab)
  
  get_acs(geography = geography,
          table = table,
          county = county,
          state = state,
          output = "tidy",
          year = 2017,
          cache_table = T,
          summary_var = summary_var, 
          geometry = FALSE, 
          cb = FALSE, 
          survey = survey) %>%
    clean_names() %>%
    left_join(acsvars) %>%
    select(-summary_moe, -variable) %>%
    select(geoid, county = name, level, levlab, estimate, everything()) %>%
    rename(!!summary_label := summary_est)
}


```


```{r}
load("~/Google Drive/SI/DataScience/Pritzker/ACS Data/acs_lst.RData")

load("~/Google Drive/SI/DataScience/Pritzker/ACS Data/acs_ethnicity_lst.RData")

gc_demo <- si_acs("B01001", county = "Guilford County", state = "NC", geography = "county", survey = "acs1")


```


```{#r median age}

age <- si_acs("B01002", geography = "county", state = "NC", survey = "acs1", county = "Guilford County")

save(age,file =  "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/age.rda")


```



```{r sex}



gc_sex <- gc_demo %>% 
  filter(level == 2) %>% 
  select(levlab, estimate, location = county)

city_sex <- cities_demo %>% 
  filter(str_detect(county, "Greensboro")|str_detect(county, "High Point")) %>% 
  filter(level == 2) %>% 
  select(levlab, estimate, location = county)

sex <- bind_rows(gc_sex, city_sex) %>% 
  mutate(location = str_remove(location, ", North Carolina"))

billboarder() %>% 
  bb_donutchart(data = gc_sex)

save(sex, file = "~/Google Drive/SI/DataScience/data/Guilford County CIP/dashboard/sex_all.rda")
#save(gc_sex, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/sex.rda")


```


```{r total}

gc_sex %>% 
  summarise(t = sum(estimate))

```


```{r ages}



gc_ages <-gc_demo %>% 
  filter(level ==3) %>% 
  select(levlab, estimate, label) %>% 
  group_by(levlab) %>% 
  summarise(total = sum(estimate)) %>% 
  spread(levlab, total) %>% 
  mutate(`0-9 Years` = sum(`Under 5 years`,`5 to 9 years` ),
         `10-19 Years` = sum(`10 to 14 years`, `15 to 17 years`, `18 and 19 years` ), 
         `20-29 Years` = sum(`20 years`, `21 years`, `22 to 24 years`, `25 to 29 years`),
         `30-39 Years` = sum(`30 to 34 years`, `35 to 39 years`), 
         `40-49 Years` = sum(`40 to 44 years`, `45 to 49 years`), 
         `50-59 Years` = sum(`50 to 54 years`, `55 to 59 years`),
         `60-69 Years`= sum(`60 and 61 years`, `62 to 64 years`, `65 and 66 years`, `67 to 69 years`),
         `70 - 79 Years` = sum(`70 to 74 years`, `75 to 79 years`), 
         `80 Years and Over` = sum(`80 to 84 years`, `85 years and over`)) %>% 
  select(24:32) %>% 
  gather(c(1:9), key = "Ages", value = "Total") %>% 
  mutate(denom = sum(Total),
         perc = round((Total/denom)*100),0) %>% 
  select(Ages, perc) %>% 
  mutate(location = "Guilford County")



cities_demo <- si_acs("B01001", geography = "place", state = "NC",  survey = "acs1")


gb_ages <- cities_demo %>% 
  mutate(location = str_remove(county, ", North Carolina")) %>% 
  filter(location == "Greensboro city") %>% 
  filter(level ==3) %>% 
  select(levlab, estimate, label) %>% 
  group_by(levlab) %>% 
  summarise(total = sum(estimate)) %>% 
  spread(levlab, total) %>% 
  mutate(`0-9 Years` = sum(`Under 5 years`,`5 to 9 years` ),
         `10-19 Years` = sum(`10 to 14 years`, `15 to 17 years`, `18 and 19 years` ), 
         `20-29 Years` = sum(`20 years`, `21 years`, `22 to 24 years`, `25 to 29 years`),
         `30-39 Years` = sum(`30 to 34 years`, `35 to 39 years`), 
         `40-49 Years` = sum(`40 to 44 years`, `45 to 49 years`), 
         `50-59 Years` = sum(`50 to 54 years`, `55 to 59 years`),
         `60-69 Years`= sum(`60 and 61 years`, `62 to 64 years`, `65 and 66 years`, `67 to 69 years`),
         `70 - 79 Years` = sum(`70 to 74 years`, `75 to 79 years`), 
         `80 Years and Over` = sum(`80 to 84 years`, `85 years and over`)) %>% 
  select(24:32) %>% 
  gather(c(1:9), key = "Ages", value = "Total") %>% 
  mutate(denom = sum(Total),
         perc = round((Total/denom)*100),0) %>% 
  select(Ages, perc) %>% 
  mutate(location = "Greensboro city")


hp_ages <- cities_demo %>% 
  mutate(location = str_remove(county, ", North Carolina")) %>% 
  filter(location == "High Point city") %>% 
  filter(level ==3) %>% 
  select(levlab, estimate, label) %>% 
  group_by(levlab) %>% 
  summarise(total = sum(estimate)) %>% 
  spread(levlab, total) %>% 
  mutate(`0-9 Years` = sum(`Under 5 years`,`5 to 9 years` ),
         `10-19 Years` = sum(`10 to 14 years`, `15 to 17 years`, `18 and 19 years` ), 
         `20-29 Years` = sum(`20 years`, `21 years`, `22 to 24 years`, `25 to 29 years`),
         `30-39 Years` = sum(`30 to 34 years`, `35 to 39 years`), 
         `40-49 Years` = sum(`40 to 44 years`, `45 to 49 years`), 
         `50-59 Years` = sum(`50 to 54 years`, `55 to 59 years`),
         `60-69 Years`= sum(`60 and 61 years`, `62 to 64 years`, `65 and 66 years`, `67 to 69 years`),
         `70 - 79 Years` = sum(`70 to 74 years`, `75 to 79 years`), 
         `80 Years and Over` = sum(`80 to 84 years`, `85 years and over`)) %>% 
  select(24:32) %>% 
  gather(c(1:9), key = "Ages", value = "Total") %>% 
  mutate(denom = sum(Total),
         perc = round((Total/denom)*100),0) %>% 
  select(Ages, perc) %>% 
  mutate(location = "High Point city")



ages <- bind_rows(gc_ages, hp_ages, gb_ages)

billboarder() %>% 
 bb_barchart(data = gc_ages, stacked = T)


#save(ages, file = "~/Google Drive/SI/DataScience/data/Guilford County CIP/dashboard/ages1.rda")
#save(gc_ages, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/ages.rda")

```



```{r race}

race_county <- acs_lst$county %>% 
  select(county, state, contains("race")) %>% gather(key = key, value = n, -state, -county) %>% separate(key, into = c("var", "age", "unit", "race"), sep = "\\.") %>% filter(age == "allages") %>% 
  filter(county == "Guilford County") %>% 
  filter(race != "hispanic") %>% 
  filter(race!="nonhispanicwhite") %>% 
  select(race,n, location = county) %>% 
  mutate(race = str_to_sentence(race)) %>% 
  mutate(race = case_when(race == "Hawaii_pacisl" ~ "Native Hawaiian or Other Pacific Islander",
                          race == "Black" ~ "Black or African American",
                          race == "Multi" ~ "Multiracial",
                          race == "Native" ~ "American Indian or Alaska Native", 
                          TRUE~race))


race_city <- acs_lst$place %>% 
  filter(state_name == "North Carolina", city == "Greensboro"|city == "High Point") %>% 
  mutate(city = case_when(city == "Greensboro" ~ "Greensboro city",
                          city == "High Point" ~ "High Point city")) %>% 
  select(city, state, contains("race")) %>% gather(key = key, value = n, -state, -city) %>% separate(key, into = c("var", "age", "unit", "race"), sep = "\\.") %>% filter(age == "allages") %>% 
  filter(race != "hispanic") %>% 
  filter(race!="nonhispanicwhite") %>% 
  select(race,n, location = city) %>% 
  mutate(race = str_to_sentence(race)) %>% 
  mutate(race = case_when(race == "Hawaii_pacisl" ~ "Native Hawaiian or Other Pacific Islander",
                          race == "Black" ~ "Black or African American",
                          race == "Multi" ~ "Multiracial",
                          race == "Native" ~ "American Indian or Alaska Native", 
                          TRUE~race))

race <- bind_rows(race_city, race_county)


#save(race, file = "~/Google Drive/SI/DataScience/data/Guilford County CIP/dashboard/race_all.rda") 
  
levels(as.factor(race_county$race))

billboarder() %>% 
  bb_donutchart(data = race_county) %>% 
  bb_donut()#chart prop here)

save(race_county, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/race.rda")


```



```{r ethnicity}

acs_ethn_county <- acs_ethnicity_lst$county%>% filter(value_type == "estimate") %>% 
  filter(county == "Guilford County") %>% 
  mutate(value = as.numeric(value),
         ethnicity = str_replace_all(ethnicity, "\\.", " ")) %>% 
  select(ethnicity, value, location = county)

acs_ethn_city <- acs_ethnicity_lst$place%>% 
  filter(state_name == "North Carolina", city == "Greensboro"|city == "High Point") %>% 
  mutate(city = case_when(city == "Greensboro" ~ "Greensboro city",
                          city == "High Point" ~ "High Point city")) %>% 
  filter(value_type == "estimate") %>% 
  mutate(value = as.numeric(value),
         ethnicity = str_replace_all(ethnicity, "\\.", " ")) %>% 
  select(ethnicity, value, location = city)

ethnicity <- bind_rows(acs_ethn_city, acs_ethn_county)

save(ethnicity, file = "~/Google Drive/SI/DataScience/data/Guilford County CIP/dashboard/ethnicity_all.rda")

billboarder() %>% 
  bb_donutchart(data = acs_ethn_county)

#save(acs_ethn_county, file = "G:/My Drive/SI/DataScience/data/Guilford County CIP/dashboard/ethnicity.rda")

```



```{r gsheet }

projects <- gs_title("projects")
act_project <- gs_read(ss=projects, ws = "Sheet1")

list <- act_project %>% 
  select(act) 

HTML(paste(list$act, sep = '<ul> <li> </li>'))



```


```{r SNAP}

snap_county <- si_acs("B22003",geography = "county", state = "NC", survey = "acs1", county = "Guilford County")

snap_c1 <- snap_county %>% 
  filter(level==2) %>% 
  filter(str_detect(label, "received Food")) %>% 
  mutate(perc = estimate/Total) %>% 
  select(location =county, perc)

snap_city <- si_acs("B22003", geography = "place", state = "NC",  survey = "acs1")

snap_c2 <- snap_city %>% 
  filter(str_detect(county, "Greensboro")|str_detect(county, "High Point")) %>% 
  filter(level==2) %>% 
  filter(str_detect(label, "received Food")) %>% 
  mutate(perc = estimate/Total) %>% 
  select(location =county, perc)

snap <- bind_rows(snap_c1, snap_c2) %>% 
  mutate(location = str_remove(location, ", North Carolina"))
  


#save(snap, file = "~/Google Drive/SI/DataScience/data/Guilford County CIP/dashboard/snap.rda")
```


